### ISSUE TITLE
Ryan's comments

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#117]
@yaronf I'm not sure we addressed all of Ryan's comments?

https://mailarchive.ietf.org/arch/msg/acme/CG3CE5Wo7LjUnvPP2V8er6OL3NQ/

**Comment by yaronf** [comment]
Quite sure we didn't. Glad you remembered his comments - more than a year ago!

**Comment by thomas-fossati** [comment]
my short term memory is really, really bad, but allow things to percolate into the deeper strata of my conscience and they won't ever be forgotten ;-)

**Comment by yaronf** [comment]
It turns out that we did implement his comments to the Sec Considerations, but not his other comments. Fixed in my PR.
