### ISSUE TITLE
ACK people that provided comments and design suggestions

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#121]
Apropos remembering, we should add at least the following folks to the ACK section:

* Ryan Sleevi
* Roman Danyliw
* Frédéric Fieau
* Sanjay Mishra
* Emile Stephan

**Comment by yaronf** [comment]
Anybody form the STIR folks?

**Comment by yaronf** [comment]
BTW Kramdown removes the accents from Frédéric, surprisingly.

**Comment by thomas-fossati** [comment]
> Anybody from the STIR folks?

right, += Jon Peterson

**Comment by yaronf** [comment]
OK. Spanish authors get accents for free. Acknowledged Frenchmen, no.
