### ISSUE TITLE
behaviour on certificate revocation

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#13]
In theory, a STAR certificate could be revoked the ACME way (https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.6).  This doesn't make much sense in a STAR environment, which relies on expiration of the short-term cert to handle key compromise.
The document should explicitly say whether the revocation interface is available to an ACME STAR client or not.

**Comment by yaronf** [comment]
I agree, and suggest that we allow two alternatives:
- Either a revokeCert URL is unavailable.
- Or it always returns "403 Forbidden" for STAR certs.

**Comment by thomas-fossati** [comment]
Unless the ACME CA is "pure" STAR, I think it's not possible dropping the revokeCert URL altogether -- I mean before reading the payload and deciding whether the cert is STAR or not.

I support the 403.

**Comment by yaronf** [comment]
I'm good with "403".
