### ISSUE TITLE
abstract lacks technical accuracy

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#139]
https://mailarchive.ietf.org/arch/msg/acme/XF0qZ5Ba2ldx4Dxyuyo6vUV8-FA/

```
Abstract: It says: "...  party access to a certificate associated with
said identifier."  This is odd wording, and it is incorrect.  The party
needs access to the private key that corresponds to the public key in
the certificate, and the certificate needs to contain the subject for
"said identifier".  Clearly, all of that should not go in the Abstract,
but what does appear in the Abstract needs to be technically accurate.
```

**Comment by russhousley** [comment]
I think it would be better to avoid the phrase "own a certificate".  Some certificate policies explicitly says that the issuer owns the certificate, and your use of "own" has nothing to do with that concept.  You are after a private key under the control of the CDN and a certificate that contains the domain name of the party performing the delegation.

**Comment by thomas-fossati** [comment]
What about the following?

OLD:
```
    This memo proposes a profile of the Automatic Certificate Management
    Environment (ACME) protocol that allows the owner of an identifier
    (e.g., a domain name) to delegate to a third party the ability to
    request and own a certificate associated with said identifier.
```
NEW:
```
    This memo proposes a profile of the Automatic Certificate Management
    Environment (ACME) protocol that allows the owner of an identifier
    (e.g., a domain name) to delegate to a third party the ability to
    request a certificate associated with said identifier and a private
    key under the sole control of the third party.    
```

**Comment by yaronf** [comment]
@thomas-fossati your new text is subtly ambiguous. I would propose (just added one word, "with"):

New:
``
    This memo proposes a profile of the Automatic Certificate Management
    Environment (ACME) protocol that allows the owner of an identifier
    (e.g., a domain name) to delegate to a third party the ability to
    request a certificate associated with said identifier and with a private
    key under the sole control of the third party.    
``

**Comment by russhousley** [comment]
Suggestion:  "... said identifier associated with a private key under the sole control of that third party."

**Comment by thomas-fossati** [comment]
> Suggestion: "... said identifier associated with a private key under the sole control of that third party."

When you join it with the preceding text the result is _"[...] request a certificate associated with said identifier associated with a private key [...]"_ which stutters a bit.

**Comment by russhousley** [comment]
Reword as you wish.  There are two key points.  First, the certificate contains the identifier that is delegated.  Second, that the third party has control of the private key, and the certificate contains the corresponding public key.
