### ISSUE TITLE
register extendedKeyUsage as OIDs

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#145]
https://mailarchive.ietf.org/arch/msg/acme/XF0qZ5Ba2ldx4Dxyuyo6vUV8-FA/

```
Section 5.6 registers a string name for each extendedKeyUsage OID.
There should be a way to provide the OID in dotted decimal format
as well.  New OIDs are being assigned all the time, and some of them
may not be registered with IANA.
```

**Comment by yaronf** [comment]
JSON Schema: `pattern` property and `oneOf`.

CDDL: `.regexp`

**Comment by yaronf** [comment]
Pushed into `main` by mistake.

The code works for JSON Schema.

However this crashes the `cddl` tool with an ugly stack trace:

``
cddl template-schema.cddl validate test/FAIL_bad_OID.json 
``

@thomas-fossati need your help!

**Comment by thomas-fossati** [comment]
Are you using Carsten's `cddl`?

On my machine:
```
CDDL validation failure (nil for {"keyTypes"=>[{"PublicKeyType"=>"rsaEncryption", "PublicKeyLength"=>2048, "SignatureType"=>"sha256WithRSAEncryption"}, {"PublicKeyType"=>"id-ecPublicKey", "namedCurve"=>"secp521r1", "SignatureType"=>"ecdsa-with-SHA512"}], "subject"=>{"country"=>"CA", "stateOrProvince"=>"**", "locality"=>"**", "commonName"=>"**"}, "extensions"=>{"subjectAltName"=>{"DNS"=>["cache.ndc.ido.example"], "URI"=>["sip:voice.ndc.ido.example"], "Email"=>["admin@ndc.ido.example"]}, "keyUsage"=>["digitalSignature"], "extendedKeyUsage"=>["serverAuth", "1.3.6gotcha!.1.4.1.311.44.3.4"]}}):
["1.3.6gotcha!.1.4.1.311.44.3.4",
 [:prim, 3],
 "[\"1.3.6gotcha!.1.4.1.311.44.3.4\", [:prim, 3], nil] -- cannot complete (1, 2) array [\"serverAuth\", \"1.3.6gotcha!.1.4.1.311.44.3.4\"] for [:array, [:member, 1, Infinity, nil, [:type1, [:text, \"serverAuth\"], [:text, \"clientAuth\"], [:text, \"codeSigning\"], [:text, \"emailProtection\"], [:text, \"timeStamping\"], [:text, \"OCSPSigning\"], [:anno, :regexp, [:prim, 3], [:text, \"^[0-9]+(\\\\.[0-9]+)*$\"]]]]]"]
["1.3.6gotcha!.1.4.1.311.44.3.4", [:prim, 3], "[\"1.3.6gotcha!.1.4.1.311.44.3.4\", [:prim, 3], nil] -- cannot complete (1, 2) array [\"serverAuth\", \"1.3.6gotcha!.1.4.1.311.44.3.4\"] for [:array, [:member, 1, Infinity, nil, [:type1, [:text, \"serverAuth\"], [:text, \"clientAuth\"], [:text, \"codeSigning\"], [:text, \"emailProtection\"], [:text, \"timeStamping\"], [:text, \"OCSPSigning\"], [:anno, :regexp, [:prim, 3], [:text, \"^[0-9]+(\\\\.[0-9]+)*$\"]]]]]"]
```

Which looks horrible but OK to me: the regexp doesn't match and the whole thing does not validate.

Nit: CDDL regexp's are XSD regular expressions, so `^` and `$` are not needed

**Comment by yaronf** [comment]
Ummm, which validator are you using? The `README.md` mentions Carsten's tool (I actually started out with a different one). Will fix the nit and close the issue.

**Comment by thomas-fossati** [comment]
```
19:28 $ gem list | grep cddl
cddl (0.8.12, 0.8.10, 0.8.9)
```
It looks like Carsten's 0.8.12.   (A bit outdated -- latest is 0.8.21 -- but works for me so I don't have strong reasons to upgrade.)

**Comment by russhousley** [comment]
I see the regex in CSR-template/template-schema.cddl, but I think there should also be text in Section 5.6.

**Comment by thomas-fossati** [comment]
I am not sure we need to say more than what is currently in table 6, which refers to the inlined schema for the syntax and the relevant section of RFC5280 for the semantic mapping.

The only thing that looks incorrect to me is that the second column in table 6 should reference Appendix B (CDDL, normative) rather than C (JSON-schema, informative).

**Comment by russhousley** [comment]
I see.  Section 3 refers to the CDDL as the specification of the CSR-template.
