### ISSUE TITLE
allow registration of SAN::otherName as OIDs

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#146]
https://mailarchive.ietf.org/arch/msg/acme/XF0qZ5Ba2ldx4Dxyuyo6vUV8-FA/

```
Section 5.6 registers a string name for each type of subjectAltName.
This include otherName, which are identified by an OID.  New OIDs are
being assigned all the time.  For example, draft-ietf-anima-autonomic-
control-plane-30 creates a new otherName.  There should be a way to
provide the the otherName OID in dotted decimal format as well.
```

**Comment by yaronf** [comment]
I wonder if this makes sense in the context of ACME, where each SAN type implies its own explicit authorization. The table in Sec. 5.6 mentions that we only support 4 specific name types. Am I missing anything?

**Comment by thomas-fossati** [comment]
I think you are right, and table 6 is very clear about which SAN we support out of the box (which doesn't include otherName).

Tangentially, this made me realise that we should probably add a ref to draft-ietf-acme-dtnnodeid (for SAN::URI) and draft-ietf-acme-email-smime (for SAN::rfc822Name) which we don't have AFAIR.

**Comment by yaronf** [comment]
I don't think we should, because we say almost nothing about authorizations.

Yes, we support non-DNS types to enable these extensions, but also any other extensions that require these SAN types.

**Comment by thomas-fossati** [comment]
WFM

**Comment by yaronf** [comment]
Closing - won't fix.

**Comment by russhousley** [comment]
This comment is not about authorizations.  Of course, for each name form in the SubjectAltName, the ACME CA needs to confirm control over the requested name.

Why are you explicitly allowing email address with no discussion of this point?  Email address raises the same concerns as the otherName.

**Comment by thomas-fossati** [comment]
> Why are you explicitly allowing email address with no discussion of this point? Email address raises the same concerns as the otherName.

The rationale (which alas is not transparent in the text) is to include only the identifiers that are defined in adopted ACME documents (DNS from RFC8555, email from I-D.ietf-acme-email-smime and URI from I-D.ietf-acme-dtnnodeid) and have therefore a well-defined authorisation mechanism.  That is a precondition for the delegation mechanism to be usable.

**Comment by russhousley** [comment]
Okay, but that would beg for a MUST statement that each entry on the SubjectAltName needs to be validate by the ACME CA with an appropriate challenge.
