### ISSUE TITLE
remove LURK ref?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#148]
https://mailarchive.ietf.org/arch/msg/acme/XF0qZ5Ba2ldx4Dxyuyo6vUV8-FA/

```
Section 1 describes [I-D.mglt-lurk-tls13] as an ongoing effort.  This
is not accurate.  The LURK BoF did not lead to a WG or an effort in an
existing WG.  I think the best way forward is to drop this reference.
```

**Comment by yaronf** [comment]
Rechecked: the wording is correct. The latest version of this draft (which, granted, should have been renamed) is less than two months old. So this is clearly ongoing work.

@russhousley.

**Comment by thomas-fossati** [comment]
Russ in https://mailarchive.ietf.org/arch/msg/last-call/PBht-iB_1bzkRraxh5WC_FrCDJc/

```
Not clear that LURK will gain acceptance, but TLS-Subcerts is about to be passed to the IESG.
```

**Comment by thomas-fossati** [comment]
We don't know if LURK is going to get traction either, but this is not the point we are trying to make with the statement:
```
   We note that other ongoing efforts address the problem of certificate
   delegation for TLS connections, specifically [I-D.ietf-tls-subcerts]
   and [I-D.mglt-lurk-tls13].
```
We only note that other solutions have been formulated to solve the same problem and cite their latest (in both cases very recent) available copy.

**Comment by thomas-fossati** [comment]
https://mailarchive.ietf.org/arch/msg/acme/VfzOZih-4gL8aIGVtzMw0K-CQxo/

```
All of the other topics have been sorted out.

Russ
```
