### ISSUE TITLE
Missing guidance for expert reviewers

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#168]
Excerpt from Lars' DISCUSS point:

```
Section 5.1, paragraph 4, discuss:
>    This document requests that IANA create the following new registry
>    under the Automated Certificate Management Environment (ACME)
>    Protocol:
>
>    *  ACME Identifier Object Fields
>
>    This registry is administered under a Specification Required policy
>    [RFC8126].

RFC8126 strongly suggests that guidance needs to be given to expert reviewers
that are supposed to review and approve requests for "Expert Review" and
"Specification Required" registries. This guidance is missing here. What's also
missing are designated contact persons and a change controller.

Section 5.6, paragraph 2, discuss:
> 5.6.  CSR Template Extensions
>
>    IANA is requested to establish a registry "STAR Delegation CSR
>    Template Extensions", with "Expert Review" as its registration
>    procedure.

Same as above.
```

**Comment by yaronf** [comment]
We plan to drop the 5.1 registry, see #171.

For 5.6, we propose to change to "Specification Required" to be in line with other ACME registries. There is no need for Change Controller (RFC 8126 says this is only needed for media types). We will specify the current authors @thomas-fossati and @yaronf as Experts.

Guidance:
* The definition must include a full CDDL definition, which the Expert will manually validate.
* The definition must include both positive and negative test cases.
* Additional requirements that are not captured by the CDDL definition are allowed but must be explicitly specified.

**Comment by larseggert** [comment]
This all sounds good, but where in RFC8126 does it say change controllers are only needed for media types?

**Comment by thomas-fossati** [comment]
> This all sounds good, but where in RFC8126 does it say change controllers are only needed for media types?

It doesn't, it only cites RFC6838 as an example of explicitly requiring a change controller.  Instead, I think we should have said that we want to keep with the ACME tradition of relying on the default change controller for registries created by RFCs in the IETF stream, i.e., the IETF itself.
