### ISSUE TITLE
Lars comments

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#169]
```
Section 1, paragraph 8, comment:
>    We note that other ongoing efforts address the problem of certificate
>    delegation for TLS connections, specifically [I-D.ietf-tls-subcerts]
>    and [I-D.mglt-lurk-tls13].  Compared to these other solutions, the
>    current document does not introduce additional latency to the TLS
>    connection, nor does it require changes to the TLS network stack of
>    either the client or the server.

This paragraph should probably be removed upon publication as an RFC?

-------------------------------------------------------------------------------
All comments below are very minor change suggestions that you may choose to
incorporate in some way (or ignore), as you see fit. There is no need to let me
know what you did with these suggestions.

Section 3.1, paragraph 10, nit:
-    e.g. by restricting field lengths.  In this regard, note that a
+    e.g., by restricting field lengths.  In this regard, note that a
+        +

Section 4.1, paragraph 3, nit:
-    This section uses specifically CDNI terminology, e.g. "uCDN" and
+    This section uses specifically CDNI terminology, e.g., "uCDN" and
+                                                         +

Section 4.1.2.1, paragraph 5, nit:
-    Unlike HTTP based redirection, where the original URL is supplanted
-               ^
+    Unlike HTTP-based redirection, where the original URL is supplanted
+               ^
```

**Comment by yaronf** [comment]
@larseggert I wonder why you recommend to remove the paragraph about other similar efforts. To me this is useful information: here are alternative solutions to the same problem, and this is how we believe our solution compares (very subjectively, granted).

If your objection is mainly to referring to them as "ongoing", we could reword to something like: 
> We note that other standardization efforts address the problem of certificate delegation for TLS connections...

**Comment by larseggert** [comment]
I suggested to remove that, because while it contained relevant info during the WG phase, this information will quickly become outdated/stale in an RFC, esp. if the other work isn't even adopted.

**Comment by yaronf** [comment]
draft-ietf-tls-subcerts is in WGLC and has some implementations, so it's very likely to be published. The LURK draft is more of a one man show. Let me reconsider, I do think pointing out related work is worthwhile.

**Comment by dr2lopez** [comment]
I'd leave a reference to TLS-subcerts, as it is very likely to be published. LURK was somehow a predecessor of all these efforts, but it seems long gone. We could add a qualifier to the reference to TLS-subcerts in those terms, or add a note for RFC editor to make such a reference in an acceptable style

**Comment by thomas-fossati** [comment]
AFAIU, LURK is alive and kicking - in fact, the latest draft has been published quite recently (Jan 2021).  The reason I'd like keeping it in is it covers the "keyless TLS" approach to delegation, similar to [Cloudflare's](https://www.cloudflare.com/en-gb/ssl/keyless-ssl/), which is different from both ACME and subcerts-based.

**Comment by dr2lopez** [comment]
Hmmm... I stand corrected: I had stopped following LURK after what I perceived as lack of interest some time ago. Then we'd need a rephrasing in terms of approaches rather than references, talking about this "keyless TLS" or the extended chain verification

**Comment by yaronf** [comment]
Will try to do that in my PR. BTW, Cloudflare's blog has a trademark symbol next to "Keyless SSL", so I will not use that term.
