### ISSUE TITLE
the delegation field should be per-order rather than per-identifier

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#171]
From the IANA Designated Expert review (Richard Barnes)

```
The "delegation" field is currently attached to the "identifier" object,
which is a bad semantic fit in a few ways. ACME orders can have multiple
identifiers, and delegations can describe multiple SAN values, yet this
design assumes singularity on both sides. This field should be moved
to the order object; in fact, if you wanted to be more radical, you could
even use it to replace the "identifiers" field in the newOrder request.
```

**Comment by yaronf** [comment]
Agreed. `delegation` should move from the `identifier` array to become a top-level parameter of `newOrder` as well as a top-level member of the `Order` object.

We would need to rephrase some text to ensure correspondence between identifiers, specifically this text:
> MUST have the delegated name as the identifier value with a delegation attribute indicating the configuration used for the identifier.

Also as a result, we can drop the new IANA registry, ACME Identifier Object Fields.

**Comment by yaronf** [comment]
cc @bifurcation.
