### ISSUE TITLE
Eric Kline's comment

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#174]
```
[ section 2.1 ]

* I know it's a list of prereqs, but I was wondering if "NDC is required"
  might want to be "NDC is REQUIRED".
```

**Comment by yaronf** [comment]
cc @ekline.

**Comment by dr2lopez** [comment]
I guess "NDC MUST" would be clearer, as this is properly speaking a requirement derived from the precondition

**Comment by thomas-fossati** [comment]
I am fine with both `MUST` and `REQUIRED`, they have equivalently strong semantics in [BCP14](https://tools.ietf.org/html/rfc2119#section-1).  It looks like capitalising the existing `required` would satisfy the principle of least action though :-)

**Comment by thomas-fossati** [comment]
Actually, looking at it a bit more, there doesn't seem to be a requirement for interop here, in fact:
* If the NDC uses a delegation object that is not configured with its account, it will receive an `unknownDelegation` error back from the IdO;
* If the supplied CSR doesn't match the template associated with the indicated delegation object, the NDC will get back a `rejectedIdentifier` or `badCSR`.

So, I'm tempted to either drop the sentence altogether, or replace it with a purely informative _"The NDC will use this template for every CSR created under the same delegation"_.

One aspect though that may need some more attention is the second bullet in the same list: _"The NDC has registered an ACME account with the IdO;"_ which is effectively a requirement on which two important aspects of the protocol are built upon:
* The delegation mapping, and
* The security of the delegation process.
I reckon a REQUIRE there would be good to add.
