### ISSUE TITLE
Nonces in GCM

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#200]
Is there a specific problem in TLS?
* Potentially relevant: https://eprint.iacr.org/2015/102.pdf
* Also https://vigilance.fr/vulnerability/TLS-obtaining-data-size-via-HTTPS-Bicycle-18648 ?

**Comment by thomas-fossati** [comment]
Also relevant: https://www.rfc-editor.org/errata_search.php?rfc=5288&rec_status=0

**Comment by thomas-fossati** [comment]
> * Potentially relevant: https://eprint.iacr.org/2015/102.pdf

The thing is there are no ciphersuites that use AES-GCM-SIV, so I don't have anything actionable to add.

> * Also https://vigilance.fr/vulnerability/TLS-obtaining-data-size-via-HTTPS-Bicycle-18648 ?

This one is an instance of web page fingerprinting attack using application packet lengths inferred from the (stream) encrypted session -- so this would also apply to any other stream cipher.  TLS 1.2 doesn't have the same padding features as 1.3 so the recommendation would be to pad at the application level.  But then would that be in scope for this document?
