### ISSUE TITLE
Raccoon Attack

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#202]
* Attack: https://raccoon-attack.com/
* Should we move away from DHE and only allow ECDHE in TLS 1.2?
* Probably enough to avoid reuse of DH public keys, see §6.3 - add a reference to Raccoon.

**Comment by yaronf** [comment]
See also related TODO at top of Sec. 4.4:

> TODO: revise after Logjam?

**Comment by thomas-fossati** [comment]
See also:
* this (pretty recent) discussion on the TLS ML https://mailarchive.ietf.org/arch/msg/tls/h7cBUg93KoU8aar1Bx22BiDyF1E/ , and
* the associated I-D https://datatracker.ietf.org/doc/html/draft-bartle-tls-deprecate-ffdhe-00

**Comment by yaronf** [comment]
At a minimum, add normative text to avoid DH reuse.
