### ISSUE TITLE
Limits on # of records

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#203]
* Should we mention limits on # of records per connection in TLS 1.2, similarly to Sec. 5.5 of RFC 8446?
* See https://datatracker.ietf.org/doc/draft-irtf-cfrg-aead-limits/02/ 
* Or even copy the numbers from 8446.
* DONE: Peter to ask Martin & Chris. The numbers for 1.2 would be the same as for QUIC and 1.3

**Comment by stpeter** [comment]
I will report back once I hear from Martin Thomson and Chris Wood about whether the numbers would be the same for TLS 1.2 as in TLS 1.3 / QUIC.

**Comment by stpeter** [comment]
tl;dr from Martin: "the bounds we establish in the draft for TLS 1.3 should apply to TLS 1.2" - and he and Chris might add something about this to their I-D. See also https://eprint.iacr.org/2018/993.pdf for further analysis.

**Comment by yaronf** [comment]
We should either reference the new text (preferred) or add an appendix to explain the bounds, since the derivation is different for TLS 1.2. More details in the mail.

**Comment by stpeter** [comment]
Agreed. I've encouraged Martin and Chris to cover this in their I-D.

**Comment by yaronf** [comment]
cc: @martinthomson
