### ISSUE TITLE
ALPACA Attack

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#204]
* High level description: https://www.theregister.com/2021/06/10/alpaca_tls_protection/
* More technical depth here: https://arstechnica.com/gadgets/2021/06/hackers-can-mess-with-https-connections-by-sending-data-to-your-email-server/
* Paper/site: https://alpaca-attack.com/

Should we worry about it? Just use it as further support for a recommendation to use ALPN?

Oops, we don't mention ALPN at all!

**Comment by thomas-fossati** [comment]
> * High level description: https://www.theregister.com/2021/06/10/alpaca_tls_protection/
> * More technical depth here: https://arstechnica.com/gadgets/2021/06/hackers-can-mess-with-https-connections-by-sending-data-to-your-email-server/
> * Paper/site: https://alpaca-attack.com/

nice!

> Should we worry about it? Just use it as further support for a recommendation to use ALPN?

There seem to be two recommendations at the TLS layer:

1.  For ALPN: enforce the behaviour prescribed in Section 3.2 of 7301 _"In the event that the server supports no protocols that the client advertises, then the server SHALL respond with a fatal "no_application_protocol" alert."_
1. For SNI: slightly change Section 3 of 6066 _"If the server understood the ClientHello extension but does not recognize the server name, the server SHOULD take one of two actions: either abort the handshake by sending a fatal-level unrecognized_name(112) alert or continue the handshake."_ removing the ability to continue with the handshake in case of name mismatch.

Did I understand it correctly?  (I will reach out to check this with the authors.)

> Oops, we don't mention ALPN at all!

ah :-)

**Comment by yaronf** [comment]
See more nuanced ALPN recommendations on their web site here: https://alpaca-attack.com/libs.html#alpn

**Comment by dr2lopez** [comment]
So are you proposing we mandate (or at least recommend) the use of ALPN?

**Comment by yaronf** [comment]
> So are you proposing we mandate (or at least recommend) the use of ALPN?

Yes. AFAIK it is widely implemented in browsers, not sure about server side. Are you saying this is going too far?
