### ISSUE TITLE
use "might behave" instead of "decide"

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#206]
Ben has an editorial suggestion regarding [Section 2.4](https://mailarchive.ietf.org/arch/msg/acme/cKMl9XjSIeGB_zjbQ-3mHFTv2Pw/):

```
I think we are in agreement on the behavior of B in the respective cases,
and thank you for writing them out clearly to anchor the discussion.
I suspect that I'm just bothered by the word "decide" -- to me it implies a
choice among several possibilities, but most of the time there is only one
possibility that will actually work, and thus not a real choice.  (What
with failure not being an option, and all ;)  If we instead used language
along the lines of "might behave" for each case, I don't think it would
seem problematic to me.
```

(See https://mailarchive.ietf.org/arch/msg/acme/cKMl9XjSIeGB_zjbQ-3mHFTv2Pw/ for full context.)

**Comment by thomas-fossati** [comment]
In his Ballot record, Ben adds:

```
[Just noting that the text about the IdO being able to decide on a
per-identity basis whether to proxy vs act as IdO remains confusing to
me, but this is the same comment I made on the previous version and I
expect no further changes to be made and no further discussion on the
topic.]
```

but still...

**Comment by dr2lopez** [comment]
Regarding the first comment, "decide" does not only imply a choice, but taking a decision on whether to progress with the request or not, so in my view the term is totally right. I am just wondering if the example you shared with Ben would be of help if added to the draft...
I must say I have no idea on how to address the second comment :-/

**Comment by yaronf** [comment]
I believe I wrote the original text and I find it just fine. Having said that, I understand Ben's comment and I suggest we address it.

Old:
> An entity implementing the IdO server role - an "ACME Delegation server" - can decide, on a per-identity case, whether to act as a proxy into another ACME Delegation server, or to behave as an IdO and obtain a certificate directly. The determining factor is whether it can successfully be authorized by the next-hop ACME server for the identity associated with the certificate request.

New:
> An entity implementing the IdO server role - an "ACME Delegation server" - may behave, on a per-identity case, either as a proxy into another ACME Delegation server, or it may behave as an IdO and obtain a certificate directly. The determining factor is whether it can successfully be authorized by the next-hop ACME server for the identity associated with the certificate request.

**Comment by dr2lopez** [comment]
Looks good to me. And more precise indeed...

**Comment by thomas-fossati** [comment]
> I must say I have no idea on how to address the second comment :-/

IIUC, the comment#2 says we could have ignored comment#1 :-). But I think Yaron's text is really good at capturing the spirit of comment#1, so +1
