### ISSUE TITLE
Add an ECDSA ciphersuite for TLS 1.2?

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#218]
See initial discussion here: #201.

**Comment by yaronf** [comment]
No compelling reason to include it, it is not a security requirement, and it's not clear that we can "move the needle".

**Comment by yaronf** [comment]
From another discussion: Here's [newer information](https://www.f5.com/labs/articles/threat-intelligence/the-2021-tls-telemetry-report), "The move to elliptic curve cryptography is slow but steady, with 25 percent of certificates now signed with the Elliptic Curve Digital Signature Algorithm (ECDSA)...".

**Comment by thomas-fossati** [comment]
Summary of an online conversation between @yaronf and @thomas-fossati:

* given the current push from LE
* given the general support in all the popular stacks
* given it's MTI in 1.3

we will recommend a couple of new ECDSA cipher suites:

* ECDHE-ECDSA-AES128-GCM-SHA256
* ECDHE-ECDSA-AES256-GCM-SHA256
