### ISSUE TITLE
Revisit "Modular Exponential vs. Elliptic Curve DH Cipher Suites"

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#232]
The 1024-bit recommendation is possibly/hopefully obsolete, even as a last resort.

**Comment by yaronf** [comment]
Also, the [Logjam attack](https://weakdh.org/) is a more specific reason to avoid these short groups.

**Comment by yaronf** [comment]
Here's a proposal:

* Remove the whole section, under the assumption that we have moved forward from the situation described there.
* Make DHE 2048 a MUST instead of SHOULD, and add a reference to Logjam.
* Mention that the latest NIST SP 800-56a has 2048 as *the minimal* DHE length.
* Move from 192 to 224 bit for ECDHE, and follow the same NIST doc where the minimal curve is P-224.

Important: 1024-bit DH is still observed in the wild, https://www.ssllabs.com/ssl-pulse/

**Comment by thomas-fossati** [comment]
> Here's a proposal:
> 
> * Remove the whole section, under the assumption that we have moved forward from the situation described there.

+1

> * Make DHE 2048 a MUST instead of SHOULD, and add a reference to Logjam.

I fully agree we should move the needle here -- although I note the LogJam recommendation (now 6 years old) is a bit more subtle (which could explain the ssl-pulse figures you've linked below?):

_Make sure any TLS libraries you use are up-to-date, that servers you maintain use 2048-bit or larger primes, and that clients you maintain reject Diffie-Hellman primes smaller than 1024-bit._

> * Mention that the latest NIST SP 800-56a has 2048 as _the minimal_ DHE length.

+1

> * Move from 192 to 224 bit for ECDHE, and follow the same NIST doc where the minimal curve is P-224.

+1 -- on vanilla implementations the computational increase for moving from 192 to 224 is relatively small, and often 192 is unoptimised, so 224 could actually perform _much_ better :-)
 
> Important: 1024-bit DH is still observed in the wild, https://www.ssllabs.com/ssl-pulse/

**Comment by thomas-fossati** [comment]
```
22:56 $ openssl speed ecdhp192
Doing 192 bits  ecdh's for 10s: 44224 192-bits ECDH ops in 9.93s
OpenSSL 1.1.1g  21 Apr 2020
                              op      op/s
 192 bits ecdh (nistp192)   0.0002s   4453.6
```

```
22:56 $ openssl speed ecdhp224
Doing 224 bits  ecdh's for 10s: 157557 224-bits ECDH ops in 9.91s
OpenSSL 1.1.1g  21 Apr 2020
                              op      op/s
 224 bits ecdh (nistp224)   0.0001s  15898.8
```
