### ISSUE TITLE
Breaking consumer documents

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#243]
@sftcd : has anyone looked at the docs referencing this BCP to check if there’s anything we may break by accident? I guess since we encouraged other IETF docs to refer to BCP195 and not RFC7525 we do owe 'em a bit of due diligence in cases where the bis RFC isn’t the same as 7525.

Yaron: I think we should have asked them to refer to RFC7525 rather than the BCP. In any case, I would claim " Appendix A. Differences from RFC 7525" resolves this issue in a sense: yes we are making some breaking changes, and here they are.

**Comment by yaronf** [comment]
https://www.arkko.com/tools/allstats/citations-rfc7525.html -- 99 red baloons

**Comment by stpeter** [comment]
I will take a cursory look at the dependent documents and see what my impressions are. We might conclude that active outreach is not needed.

**Comment by thomas-fossati** [comment]
Not sure about the heuristics used by Jari's tool to do the extraction, but https://datatracker.ietf.org/doc/rfc7525/referencedby/?full=True shows 266 documents (188 of which are RFCs)

**Comment by yaronf** [comment]
> Not sure about the heuristics used by Jari's tool to do the extraction, but https://datatracker.ietf.org/doc/rfc7525/referencedby/?full=True shows 266 documents (188 of which are RFCs)

The list has many duplicates (with and without the BCP195 label).

**Comment by yaronf** [comment]
https://docs.google.com/spreadsheets/d/1RChcYHhv_oHfjL7nHuvlo9tS_zTUfdn5s7vTvlhKVU4/edit?usp=sharing

**Comment by thomas-fossati** [comment]
> https://docs.google.com/spreadsheets/d/1RChcYHhv_oHfjL7nHuvlo9tS_zTUfdn5s7vTvlhKVU4/edit?usp=sharing

great idea Yaron

**Comment by yaronf** [comment]
> > https://docs.google.com/spreadsheets/d/1RChcYHhv_oHfjL7nHuvlo9tS_zTUfdn5s7vTvlhKVU4/edit?usp=sharing
> 
> great idea Yaron, I'll pick up some of the entries not yet populated

Thanks. I enabled write access for you and Peter. It's very boring but also very fast: the vast majority of citations are generic.

**Comment by yaronf** [comment]
Discussion: Thomas to publish the spreadsheet to UTA. Close.
