### ISSUE TITLE
Requiring "supported_versions"

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#253]
RFC 8446 allows (in Sec. 1.3) but does not require TLS 1.2 servers to use the `supported_versions` extension (Sec. 4.2.1) in TLS version negotiation. Do we add such a requirement?

**Comment by yaronf** [comment]
Discussion: Peter to post to the TLS ML.

**Comment by stpeter** [comment]
Done. Discussion there seems to agree with us in not recommending supported_versions for TS 1.2 implementations.

**Comment by yaronf** [comment]
Yep. Closing the issue.
