### ISSUE TITLE
Strengthen TLS Session Resumption Recommendations

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#262]
Ilari Liusvaara suggests that the recommendations given are not sufficient for security.

To actually give any forward security, with any timeframe, an server
implementation supporting TLS 1.2 session tickets MUST:

1) Rotate ticket keys periodically, AND
2) Securely destroy the old ticket keys, AND
3) Refuse to resume too old sessions.

Failure to do so does not just expose resumed connections to
compromise, it exposes all connections where client sent the session
ticket extension to compromise, regardless of if the sessions were
ever resumed or not.

The last one is about age of session, not age of ticket. Session can be
older than the ticket. These requirements follow from rather nasty
interaction of the following properties of TLS 1.2 session tickets:

1) Client can initiate handshake without proof-of-possession of the
   session ticket key.
2) The ticket is returned unencrypted.
3) The server can update the ticket.
4) There is no ratcheting of keys.

TLS 1.3 session tickets do not have three of these properties. As
consequence, e.g.:

1) Sending session ticket never compromises the connection.
2) Even without DH, only connections using ticket with compromised
   session ticket encryption key are compromised.

**Comment by yaronf** [comment]
Need more clarity on the attack described here, specifically: "the ticket is returned unencrypted".

**Comment by yaronf** [comment]
https://blog.filippo.io/we-need-to-talk-about-session-tickets/
