### ISSUE TITLE
Strengthen TLS Renegotiation Recommendations

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#263]
Ilari Liusvaara suggests that Section 3.5 needs to be strengthened to say that that "all TLS 1.2 implementations MUST implement renegotiation_info, regardless of if renegotiation is implemented or not" because "it is not safe for client to connect to TLS 1.2 server that does not support renegotiation_info, regardless of if either endpoint actually implements renegotiation."

**Comment by thomas-fossati** [comment]
I think the suggestion is correct.  We should be safe assuming that, 12 years after publication of RFC5746, interoperability with legacy server is not a concern anymore.  In fact, the level of [support for secure renegotiation](https://en.wikipedia.org/wiki/Comparison_of_TLS_implementations#Extensions) looks high enough to justify the leap.

So, we should add something like:
* client MUST send `renegotiation_info`
* If server does not acknowledge the extension, client MUST abort the handshake, and MUST generate a fatal `handshake_failure` alert prior to terminating the connection.

(This is basically taking [Section 4.1 of RFC5746](https://www.rfc-editor.org/rfc/rfc5746.html#section-4.1) and turning it up a notch by dropping the interoperability concern.)
