### ISSUE TITLE
Adjust SNI Text about ALPACA Attack

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#264]
Ilari Liusvaara suggests that the text in Section 3.7 needs to be adjusted because "It is not possible for server to acknowledge different SNI hostname. The server version of server_name extension always has an empty payload."

**Comment by stpeter** [comment]
Let's double-check what's in https://www.usenix.org/system/files/sec21-brinkmann.pdf

**Comment by stpeter** [comment]
The paper talks about implicit detection whether the hostname is hosted at the server, not explicit acknowledgement from the server.

**Comment by yaronf** [comment]
Just for the record, our text is taken directly from https://alpaca-attack.com/libs.html#sni

> We also recommend that clients abort the handshake if the server acknowledges the SNI hostname with a different hostname than the one sent by the client. 

I guess I misread that text. RFC 6066 to the rescue:

> If there is a mismatch between the server name used by the client application and the **server name of the credential chosen by the server**, this mismatch will become apparent when the client application performs the server endpoint identification, at which point the client application will have to decide whether to proceed with the communication.
