### ISSUE TITLE
Strengthen Recommendation about ECDH Exponent Reuse

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#267]
Ilari Liusvaara claims regarding Section 6.4 that reusing ECDH exponents is insecure unless one either:

1) Checks for point validity, or
2) Uses montgomery ladder with twist-secure curve.

He further states:

"Currently the only curves in TLS satisfying 2) are x25519 and x448. For
any other elliptic curve, reusing exponents without validating points
is insecure. Few thousand connection attempts at most is sufficient
for recovering the ECDH private key, which compromises any connection
that used it."

**Comment by thomas-fossati** [comment]
Ilari's comment looks right to me.

[Section 6.4](https://www.ietf.org/archive/id/draft-ietf-uta-rfc7525bis-04.html#section-6.4) only mentions EC without really describing what is the impact on security associated with private key reuse.  In fact, the recommendations only seem to focus on FF.  So there is a bit more than just strengthening to do here :-)

In the case of EC, the _"major security issues"_ connected with reuse of the private key are linked to missing input validation -- specifically, implementations that use the received points without first checking they belong to the curve.  This is the "invalid-curve" attack described in ["Differential Fault Attacks on Elliptic Curve Cryptosystems"](https://cr.yp.to/bib/2000/biehl-elliptic.pdf).  A non-laddering implementation (using both x- and y-coordinates) can be compromised (i.e., the private key is exposed after a bunch of trials that carefully manipulate the curve) if the implementation doesn't check whether the peer's public key satisfies the chosen curve equation (to really be pedantic, that the point is in the prime order subgroup that the generator is in).  A laddering implementation (using x- only coordinates) mitigates the attacker manipulative power by killing one degree of freedom.  However, to stay completely safe you'd need a curve with "twist security" (i.e., those mentioned by Illari.)

So we should add text that roughly says: "If the selected curve has no twist security (i.e., Curve25519, Curve448), the implementation MUST check that the received public key belongs to the selected curve." or something to that effect.
