### ISSUE TITLE
Modify Text about status_request_v2 Extension

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#268]
Ilari Liusvaara states that the status_request_v2 extension (mentioned in Section 6.5) is not widely supported and suggests that it might not be appropriate to recommend its use.

**Comment by stpeter** [comment]
My opinion is that in this case it's fine, since we are trying to help implementations future-proof their ability to handle certificate revocation.

**Comment by yaronf** [comment]
> My opinion is that in this case it's fine, since we are trying to help implementations future-proof their ability to handle certificate revocation.

@stpeter To clarify: you mean it's fine to keep the recommendation?

**Comment by stpeter** [comment]
Yes, I think it's fine to keep the recommendation.

**Comment by yaronf** [comment]
Will discuss with Nick S.: status_request_v2.

**Comment by yaronf** [comment]
Hmmm, this is from RFC 8446:
>Note: The status_request_v2 extension [RFC6961] is deprecated. TLS 1.3 servers MUST NOT act upon its presence or information in it when processing ClientHello messages; in particular, they MUST NOT send the status_request_v2 extension in the EncryptedExtensions, CertificateRequest, or Certificate messages.

IMO this means we should remove status_request_v2 from the text, maybe just mention it in the introductory text as not widely implemented or deprecated.

Also, our bullet #3 in Sec 6.5 is probably incorrect anyway.
