### ISSUE TITLE
Modify Text about OCSP

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#269]
Ilari Liusvaara states (with respect to Section 6.5):

> Furthermore, in context of WebPKI, the support for CA OCSP is really
> poor. Major intermediates lack OCSP entirely, or the responses have
> really long lifetimes (up to the 1 year maximum). Effective revocation
> of WebPKI CAs basically requires proprietary mechanisms.

**Comment by yaronf** [comment]
Add a bullet discussing OCSP lack of support for CA certs.
