### ISSUE TITLE
Justify Exclusion of Certificate Transparency

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#273]
Rich Salz suggests:

> And okay if you don’t want to mention certificate transparency, but either 
> include that or make explicit that for XXX reasons you’re not doing so.

**Comment by stpeter** [comment]
@richsalz 7525bis is about TLS, not PKIX. Perhaps we should cover CT in 6125bis instead?

**Comment by richsalz** [comment]
But CT also can be used in TLS, just like "OCSP stapling."  Look at the tail end of 6.5.

**Comment by stpeter** [comment]
It's not clear what kind of text you're suggesting. Perhaps we should take this to the list.

**Comment by stpeter** [comment]
I will follow up.

**Comment by stpeter** [comment]
We haven't seen support for this on the list, so I'm provisionally closing this issue. If the facts on the ground change, we can re-open it.
