### ISSUE TITLE
References

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#303]
* [x] _"[...] encourage systems to move to TLS 1.3."_: add a reference to RFC 8446

* [x] Update DTLS 1.3 reference to RFC9147

* [x] add informative references for SMTP, IMAP, POP3, SIP, XMPP, IRC, SRTP

* [x] Can we add the blog post (https://blog.filippo.io/we-need-to-talk-about-session-tickets/) as reference, and take a stable screenshot of it to include as reference in this document?
  * Removed in favour of Springall's et al. IMC paper (as per [comment](https://github.com/yaronf/I-D/issues/303#issuecomment-1131258761))

* [x] Add reference to HTTP/2 (draft-ietf-httpbis-http2bis-07)

**Comment by yaronf** [comment]
Not sure if there's a common way/tooling at the IETF to "take a snapshot" of a blog post (and what it means for copyright etc.). This particular blog doesn't mention any specific license so we should assume it is indeed copyrighted.

cc @fpalombini.

**Comment by stpeter** [comment]
I'll ask the RPC if they have a best practice for blog posts. We could, of course, point to the Wayback Machine.

**Comment by yaronf** [comment]
Re: Filippo's blog post, from Peter:

Following some links, I conclude that this paper looks like a good
replacement:

https://aaspring.com/imc2016/crypto-shortcuts.pdf

"Measuring the Security Harm of TLS Crypto Shortcuts"
Drew Springall, Zakir Durumeric†, J. Alex Halderman†
IMC 2016 November 14–16, 2016, Santa Monica, CA, USA
(c) 2016 Copyrightheldbytheowner/author(s).
ACM ISBN 978-1-4503-4526-2/16/11.
DOI: http://dx.doi.org/10.1145/2987443.2987480
