### ISSUE TITLE
Should the document update TLS and DTLS?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#304]
This would provide an easy link for implementers to more easily find this BCP.

**Comment by yaronf** [comment]
IMO this ship has sailed when TLS 1.3 obsoleted TLS 1.2.

The majority of recommendations in our document apply to TLS 1.2, so this solution wouldn't work.

**Comment by stpeter** [comment]
Presumably @fpalombini meant that 7525bis would Update 8446 and 9147?

**Comment by fpalombini** [comment]
Yes, that's what I was thinking - however this comment was just to make sure the wg has considered it, I don't have a strong opinion... Update is quite an unclear header anyway, and in this case it can be used or not, but it should be a conscious decision.
