### ISSUE TITLE
Session ticket validity

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#305]
_"session ticket validity SHOULD be limited to a reasonable duration (e.g., half as long as ticket key validity)."_

* Why this is not a MUST, i.e. what is the expected exception case?
* It is hard to define what a "reasonable duration" is, maybe something more can be added here.

**Comment by yaronf** [comment]
Change to MUST, similar to the preceding paragraph.

**Comment by yaronf** [comment]
Also, "reasonable duration" is clear in the context of preceding paragraphs.
