### ISSUE TITLE
unclear paragraph in 3.1.1

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#309]
_"We note that as long as TLS 1.2 is still allowed by a particular implementation, even if it defaults to TLS 1.3, implementers MUST still follow all the recommendations in this document."_

* Unclear what this paragraph means

**Comment by stpeter** [comment]
Perhaps:

  Even if a TLS implementation defaults to TLS 1.3, as long as it supports TLS 1.2 it MUST follow all the recommendations in this document.
