### ISSUE TITLE
wording ("include" vs "be based on")

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#310]
_"Similarly, we RECOMMEND that new protocol designs that embed the TLS mechanisms (such as QUIC has done [RFC9001]) include TLS 1.3"_

* I would not say "include" but really say "be based on" as no one new
should make something based on TLS 1.2.

**Comment by stpeter** [comment]
> Similarly, new protocol designs that embed the TLS mechanisms (such as QUIC has done [RFC9001]) SHOULD be based on TLS 1.3
