### ISSUE TITLE
session resumption performance negated by current recommendation?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#313]
_"In order to gain forward secrecy, this document recommends that server implementations SHOULD respond with a "key_share", to complete an ECDHE exchange on each session resumption."_

* Doesn't this mostly negate the "essential performance feature" of TLS session resumption?

**Comment by yaronf** [comment]
Yes, we took an extreme position here.

How about adding: Implementations MAY limit the use of key_share per local policy, e.g. may use it only for sessions that are older than X hours.

cc: @letoams

**Comment by yaronf** [comment]
Better wording:

As a more performant alternative, server implementations MAY refrain from responding with a key_share until a certain amount of time (measured in days) has passed since the last ECDHE exchange.

**Comment by letoams** [comment]
On May 21, 2022, at 13:45, Yaron Sheffer ***@***.***> wrote:
> 
> ﻿
> Better wording:
> 
> As a more performant alternative, server implementations MAY refrain from responding with a key_share until a certain amount of time (measured in days) has passed since the last ECDHE exchange
> 

Aren’t most resumptions due ti sleeping phones etc that are in the order of minutes or maybe an hour?

I don’t expect resumptions after a day are common. Which would mean the whole point of resumption is still lost based on this new text.

I believe more in the reverse. If within a few hours, don’t do key_share. After a few hours, do key_share. But that is the opposite of what you seem to want ?

Paul

**Comment by yaronf** [comment]
Paul, I guess my wording was unclear. I actually agree with you:

>  If within a few hours, don’t do key_share. After a few hours, do key_share.

But note that if we have a session resumption, say, once every hour, at *some point* we want key_share to happen - otherwise we'd never have FS. I was trying to capture that in my text.

**Comment by stpeter** [comment]
On this point...

>     * Doesn't this mostly negate the "essential performance feature" of TLS session resumption?

The document documents best current practices for security, not performance.

**Comment by letoams** [comment]
On May 23, 2022, at 17:12, Peter Saint-Andre ***@***.***> wrote:
> 
> ﻿
> On this point...
> 
> * Doesn't this mostly negate the "essential performance feature" of TLS session resumption?
> The document documents best current practices for security, not performance
> 

But then it should say “do not use session resumption”.

Paul

**Comment by yaronf** [comment]
> On this point...
> 
> > Doesn't this mostly negate the "essential performance feature" of TLS session resumption?
> 
> The document specifies best current practices for security, not performance.

For the record, I disagree with Peter on this point. To me the words "best practices" imply a _balanced_ approach that can work for the majority of use cases. In this case, it should be balanced between security and performance requirements.

**Comment by letoams** [comment]
On Thu, 19 May 2022, Yaron Sheffer wrote:

> Yes, we took an extreme position here.
> 
> How about adding: Implementations MAY limit the use of key_share per local policy, e.g. may use it only for sessions that are older than X hours.

Works for me.

Paul
