### ISSUE TITLE
SMTP ALPN registration suggested in a passive-aggressive way?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#314]
_"Protocol developers are strongly encouraged to register an ALPN identifier for their protocols.  This applies to new protocols, as well as well-established protocols such as SMTP."_

* This seems like a directive in an RFC to the IETF - get an ALPN for SMTP. We should just start that process instead of passive aggressively writing that in an RFC :)

**Comment by stpeter** [comment]
s/such as SMTP//

In any case it doesn't seem passive aggressive to me - there's only so much that we can do in this document, and registering ALPN identifiers for application protocols is out of scope.
