### ISSUE TITLE
missing rationale for recommending P-256 over its NIST siblings

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#315]
_"When using ECDSA signatures for authentication of TLS peers, it is RECOMMENDED that implementations use the NIST curve P-256."_

* Why only P-256? Why not P-384 or P-521 ?

**Comment by yaronf** [comment]
People are free to use stronger ciphers of course. But we only recommend a small set in support of interoperability. P-256 is popular and the community consensus is that it is strong enough.

cc @letoams
