### ISSUE TITLE
LogJam's implications stated too weakly?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#316]
_"The Logjam attack [Logjam] further demonstrates that 1024-bit Diffie Hellman parameters should be avoided."_

* Why is this should a lowercase? Also why not simply a "MUST NOT use"

**Comment by yaronf** [comment]
This text is part of the informative ("rationale") part of the section. The 2nd paragraph of the section is normative and REQUIRES 2048 or more.

cc: @letoams
