### ISSUE TITLE
Abstract -- wording

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#317]
* The abstract is copied from its 7 years old predecessor, which feels a little dated when it again claims _"Over the years […]."_ Perhaps a better way is a more generic txt. For example see RFC 8247.

_"This document provides recommendations for improving the security of deployed services that use TLS and DTLS."_

* That sounds a bit arrogant. Good deployments might have nothing to improve.  Just state this document provides the latest recommendations.

**Comment by yaronf** [comment]
The current abstract seems to be more appropriate for a document that's focused on security, rather than interop.

Adopt Peter's wording.
