### ISSUE TITLE
obsolete wording (assumes 1.2 is the latest and greatest)

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#319]
_"In fact, the cipher suites recommended by this document for TLS 1.2 (Section 4.2 below) are only available in this version."_

* Why are they not in TLS 1.3 ? :P Or are they?

_"TLS 1.1 and 1.2 never negotiate 40-bit or 56-bit export ciphers."_

* This (misleadingly) suggests TLS 1.3 might however do this?

**Comment by stpeter** [comment]
Suggestion:

> TLS 1.2 never negotiates 40-bit or 56-bit export ciphers and such ciphers are not supported at all in TLS 1.3.
