### ISSUE TITLE
is 1.3 "considerably" flexible WRT cipher suite selection? 

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#323]
_"TLS and its implementations provide considerable flexibility in the selection of cipher suites."_

* I wouldn't say that for TLS 1.3 ? It does still apply to TLS 1.2.

**Comment by stpeter** [comment]
Suggestion:

> TLS 1.2 provided considerable flexibility in the selection of cipher suites. Unfortunately, the security of some of these cipher suites has degraded over time to the point where some are known to be insecure (this is one reason why TLS 1.3 restricted such flexibility).
