### ISSUE TITLE
wording around the exact number of security bits

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#325]
_"Implementations SHOULD NOT negotiate cipher suites that use algorithms offering less than 128 bits of security.  Rationale: Cipher suites that offer between 112-bits and 128-bits of security are not considered weak at this time."_

* These sentences together lead to a weird case for 128. Even though it looks a little weird, I would say either "between 112-bits and 127-bits" or "more than 112-bits but less than 128-bits".

* Also, how long have we had 128 bit ciphers? Can we really not say MUST NOT instead of SHOULD NOT for the 112-127 range? Also in light of Grover's algorithm that brings 256 back to effectively 128?

**Comment by stpeter** [comment]
"more than 112-bits but less than 128-bits" WFM

**Comment by yaronf** [comment]
And to be clear, post-quantum crypto is out of scope for this document.
