### ISSUE TITLE
forward secrecy wording

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#326]
_"Rationale: Forward secrecy (sometimes called "perfect forward secrecy") prevents the recovery of information that was encrypted with older session keys, thus limiting the amount of time during which attacks can be successful.  See Section 7.3 for a detailed discussion."_

* I think this should be rewritten a little? It's not that attack time is limited, but really the exposure after a successful attack. Eg if the vulnerability is not fixed, PFS won't help you as for each session the attacker is either still there or regains access using the same vulnerability. I would more clearly say "limits how far back in time data can be decrypted when an attack is successful".

**Comment by stpeter** [comment]
"limits how far back in time data can be decrypted when an attack is successful" WFM
