### ISSUE TITLE
Deterministic signatures and their risks

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#352]
4.2: there's been some cfrg [1] discussion (but not much and without so far reaching a conclusion) on deterministic signatures (RFC6979) and fault injection attacks. I wonder if we want to say anything about that? It might be worth just adding a reference that describes the problem, but I don't think we can expect the cfrg discussion to have resolved before this gets published. Those attacks are probably not that important for a typical TLS server but more interesting for small devices with TLS servers so maybe it's a bit too niche a concern to include?

[1] https://datatracker.ietf.org/meeting/113/materials/slides-113-cfrg-signatures-deterministic-vs-randomized-00

cc @sftcd

**Comment by thomas-fossati** [comment]
FYI, I am also tracking this for draft-ietf-uta-tls13-iot-profile (https://github.com/thomas-fossati/draft-tls13-iot/issues/25).

I wonder whether that document is a better place for discussing the topic.

**Comment by sftcd** [comment]
On 27/05/2022 16:27, Thomas Fossati wrote:
> FYI, I am also tracking this for draft-ietf-uta-tls13-iot-profile (https://github.com/thomas-fossati/draft-tls13-iot/issues/25).
> 
> I wonder whether that document is a better place for discussing the topic.
> 

That does sound better, certainly if any level of detail
is to be included. For 7525bis, just a mention/reference
is probably fine.

S.
