### ISSUE TITLE
GenArt Editorials

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#355]
From @timevens:

* Section 1, introduction; incorrectly states "Datagram Transport Security Layer (DTLS)" when it should be "Datagram Transport Layer Security (DTLS)"

* Can update [I-D.ietf-tls-dtls13] to [RFC9147].

* "Sec. of" is used instead of "Section of" in the document.  Normally this would be consistent throughout the document.

**Comment by thomas-fossati** [comment]
> Can update [I-D.ietf-tls-dtls13] to [RFC9147]

this has been already taken care of when addressing AD review
