### ISSUE TITLE
GenArt: more "strict" wording

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#356]
From @timevens:

In section 3.2, the first bullet point makes sense, but does the below
need to be there?

>   "Because dynamic upgrade methods depend on negotiations
    that begin over an unencrypted channel (e.g., the server might
    send a flag indicating that TLS is supported or required), they
    are subject to downgrade attacks (e.g., an attacker could remove
    such indications); if the server does not indicate that it
    supports TLS, a client that insists on TLS protection would simply
    abort the connection, although the details might depend on the
    particular application protocol in use. In any case, ..."

Considering this ends with "In any case" I tend to lean towards not
mentioning the wordy description of dynamic upgrade methods. For
example, how about the below?

>  Many existing application protocols were designed before the use
    of TLS became common.  These protocols typically support TLS in
    one of two ways: either via a separate port for TLS-only
    communication (e.g., port 443 for HTTPS) or via a method for
    dynamically upgrading a channel from unencrypted to TLS-protected
    (e.g., STARTTLS, which is used in protocols such as SMTP and
    XMPP).  Regardless of the mechanism for protecting the communication
    channel, TLS-only port or a dynamic upgrade method, what matters is
    the end state of the channel.  When TLS-only communication is
    available for a certain protocol, it MUST be used by implementations
    and MUST be configured by administrators.  When a protocol only supports
    dynamic upgrade, implementations MUST enable a strict local policy
    (a policy that forbids fallback to plaintext) and administrators
    MUST use this policy.

**Comment by stpeter** [comment]
WFM
