### ISSUE TITLE
Clarify "stolen ticket key" scope (TEK or SK or either?)

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#367]
https://datatracker.ietf.org/doc/review-ietf-uta-rfc7525bis-07-secdir-lc-kaduk-2022-06-01/

Separately, I have in my PR attempted to impose a distinction between the
"ticket-encryption key" (private to the server) and the "session key" (the
output of the handshake, shared by both client and server and used to
encrypt traffic).  I am not actually sure if the "stolen ticket key"
phrase is intended to refer to the "ticket-encryption key" or the "session
key" (or either), so some clarification would be appreciated.
```

cc @kaduk

**Comment by stpeter** [comment]
See https://github.com/yaronf/I-D/pull/386

**Comment by stpeter** [comment]
Fixed by https://github.com/yaronf/I-D/pull/386
