### ISSUE TITLE
Earlier than 1.2 is deprecated

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#377]
1. _"Those who implement and deploy TLS and DTLS, in particular versions 1.2 or earlier of these protocols"_

Delete "or earlier". As these versions are "MUST NOT negotiate". Might be good to mention this deprecation in the introduction.

2. _"Clients SHOULD include TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 as the first proposal to any server, unless they have prior knowledge that the server cannot respond to a TLS 1.2 client_hello message."_

I would delete ", unless ...". This does not align with MUST NOT negotiate 1.1

**Comment by stpeter** [comment]
Delete ", in particular versions 1.2 or earlier of these protocols,"

**Comment by stpeter** [comment]
Delete ", unless they have prior knowledge that
   the server cannot respond to a TLS 1.2 client_hello message."
