### ISSUE TITLE
ciphersuite guidelines += SHOULD negotiate AEAD?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#381]
* §4.1. I am missing a recommendation related to AEAD. I would make sense to add that "Implementations SHOULD NOT negotiate non-AEAD cipher suites."

**Comment by yaronf** [comment]
While this decision was taken for TLS 1.3 and is taken into account in our specific ciphersuite recommendations, we do not think it is appropriate as a general recommendation for TLS 1.2 implementations, with all their legacy baggage.
