### ISSUE TITLE
Phasing out RSA-2048 and 2048-bit DH keys

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#383]
* The document should talk about the need to start phasing out RSA-2048 and 2048-bit DH keys which both gives 112-bit security. BSI requires that RSA-2048 disabled by January 2023. CA Browser forum has already forbidden RSA-2048 for use with code signing.

**Comment by stpeter** [comment]
This advice is prospective, not current. We see it as a no-op.
