### ISSUE TITLE
No 7457bis ?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#416]
_Comment by @evyncke_

I find a little weird that the legacy 'attack' document, RFC 7457, is not updated, but that the new attacks (the updated content of RFC 7457) are described in this document. No hard feeling though, and thanks for the warning text in [section 1](https://www.ietf.org/archive/id/draft-ietf-uta-rfc7525bis-09.html#section-1)

**Comment by stpeter** [comment]
In our email thread with @evyncke I apologized for this oversight. Perhaps the authors were too lazy. :-) Closing this one.
