### ISSUE TITLE
Section 1

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#417]
_Comment by @evyncke_

~~~ 
   Therefore this document replaces [RFC7525], with an explicit goal to
   encourage migration of most uses of TLS 1.2 to TLS 1.3.
~~~
Should it be stated with 'RECOMMEND' ?

**Comment by thomas-fossati** [comment]
Surely that "encourage" is effectively a "RECOMMEND" as ∑ of all the concrete SHOULDs/MUSTs that the document makes further down towards the goal of promoting 1.3 and (a highly profiled use of) 1.2. However, I wouldn't utilise a RFC2119 key word in that context because as a reader I wouldn't know what action is required on my side to fulfil the requirement -- unless I read the rest of the document :-)

**Comment by stpeter** [comment]
I think we can close this now - but @evyncke let us know if you have concerns.
