### ISSUE TITLE
Section 1 what is meant by "stronger"

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#418]
_Comment by @evyncke_

~~~ 
   Furthermore, this
   document provides a floor, not a ceiling, so stronger options are
   always allowed (e.g., depending on differing evaluations of the
   importance of cryptographic strength vs. computational load).
~~~
While the astute readers will understand what is meant by 'stronger', should this document be clear on what is meant by 'stronger' in each subsequent sections ?

**Comment by stpeter** [comment]
Via email I suggested that we expand the relevant paragraph in the Terminology section:

>    A number of security-related terms in this document are used in the
>   sense defined in [RFC4949], including "attack", "authentication",
>   "certificate", ..., "self-signed certificate", "strength", and
>   "strong". 

(Naturally we'd want to add any other terms that are relevant, thus the "..." :-)
