### ISSUE TITLE
Section 3.7 ESNI as a SHOULD ?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#422]
_Comment by @evyncke_

Shouldn't ESNI be a normative "SHOULD" ? Or is the non-normative text "just" to avoid forming a cluster with ESNI draft ? Which would be sad...

**Comment by thomas-fossati** [comment]
Whilst the [TLS milestones](https://datatracker.ietf.org/wg/tls/about/) list ECH as due to IESG in March 2021, the draft is still very much in the making -- it's not even gone through WGLC yet.  So, it'd be unwise for this document to normatively depend on it.  The current choice of words suggests a strong recommendation without creating the bureaucratic troubles that we'd incur if we made the reference normative...

**Comment by evyncke** [comment]
I understand the reasoning but I am afraid that this is NOT "the right thing to do". There is a reason behind the split of normative and informative references ;-)

What do you think @martinduke ?

**Comment by stpeter** [comment]
There is always debate about such references. It's not clear that a protocol still being hashed out in a WG (even a protocol as important as ESNI) can be reasonably considered a best *current* practice, given that it's far from stable.

**Comment by martinduke** [comment]
@evyncke What is this about? I think you meant someone else?

**Comment by evyncke** [comment]
@martinduke sorry, I meant @fpalombini the responsible AD but selected the wrong line :-O

> @evyncke What is this about? I think you meant someone else?

Francesca, time allowing, what do you think about this move from normative to informative for a reference to avoid a normative link/cluser/dependency with the ESNI I-D ?

**Comment by letoams** [comment]
On Thu, 14 Jul 2022, Peter Saint-Andre wrote:

> Francesca is going on leave very soon. Let's cc https://github.com/letoams so that Paul Wouters is in the
> loop. Oops, that should have been @letoams :-)

I prefer @paulwouters over @letoams :)

Paul

**Comment by stpeter** [comment]
Noted! :-)
