### ISSUE TITLE
Section 4.1 post-quantum crypto

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#423]
_Comment by @evyncke_

A little surprised by the absence of any "post-quantum crypto" reference in this introduction text.

**Comment by thomas-fossati** [comment]
NISTIR 8413 has just been published (last week) and we now have the first bunch of vetted PQC primitives for PK encryption, key establishment and digital signatures. The IETF was waiting on the NIST process to complete, so I guess it's time we start with incorporating the new algorithms in to the relevant protocols, including TLS and PKIX.
But first we need that to happen, then gain some deployment experience (esp. around the bandwidth/computational complexity/security trade-offs, which I expect to be *very interesting*), and only then best practices will emerge.  I am quite confident that by the time 7525ter will come out we'll have something to say, but now it's really too soon.  That's the reason why we decided to remain silent.

**Comment by stpeter** [comment]
I think the best we can say is "there's work underway, watch this space" (perhaps with a pointer to the NIST initiative).

**Comment by yaronf** [comment]
Yes, but I would avoid pointing to NIST, because it raises more questions than it answers re: how will IETF standards be derived from the NIST process.
