### ISSUE TITLE
integrity limits apply to QUIC too (not just DTLS)

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#441]
```
(4.4) In the case of QUIC, it is not the case that a single decryption
failure leads to failure of the TLS connection.
```

cc @martinduke

**Comment by stpeter** [comment]
In reply to Martin's email, I suggested:

>   The latter applies to DTLS and QUIC but not to TLS itself, since TLS
>   connections are torn down on the first decryption failure.

**Comment by martinduke** [comment]
SGTM
