### ISSUE TITLE
is SHA-256 the floor?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#455]
```
   When using RSA, servers MUST authenticate using certificates with at
   least a 2048-bit modulus for the public key.  In addition, the use of
   the SHA-256 hash algorithm is RECOMMENDED and SHA-1 or MD5 MUST NOT
   be used ([[RFC9155](https://datatracker.ietf.org/doc/rfc9155/)], and see [CAB-Baseline] for more details).

So, for clarity, this would presumably mean that SHA-256 is also preferred over say SHA-512?  Is that the intention?  Or would it be better if the SHOULD allowed stronger ciphers?
```

cc @rgwilton

**Comment by thomas-fossati** [comment]
In the Introduction we say:
```
   [...] Furthermore, this
   document provides a floor, not a ceiling, so stronger options are
   always allowed (e.g., depending on differing evaluations of the
   importance of cryptographic strength vs. computational load).
```

Readers are always free to choose stronger algorithms if they want to.

**Comment by stpeter** [comment]
@thomas-fossati that's true, although it can't hurt here to say "SHA-256 or stronger" IMHO.

**Comment by thomas-fossati** [comment]
> @thomas-fossati that's true, although it can't hurt here to say "SHA-256 or stronger" IMHO.

absolutely 👍

**Comment by thomas-fossati** [comment]
> > @thomas-fossati that's true, although it can't hurt here to say "SHA-256 or stronger" IMHO.
> 
> absolutely 👍

However, unless your threat model involves an adversary with a quantum computer, 256 is as good as 384 or 512 (and is slightly more concise on the wire).  So, if your cert is short-lived, going higher than 256 is not convenient.

**Comment by stpeter** [comment]
Good point. Let's discuss this in our authors' meeting next week.

**Comment by stpeter** [comment]
@thomas-fossati Do you think that we need to add a few words about why SHA-256 is good enough? If not, I think we can close this issue based on our email thread with @rgwilton
