### ISSUE TITLE
Incorporate 2-level delegation diargram in draft

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#46]
As SVG, if it works in the text (maybe as a separate appendix) and if the diagram is not overly complex.

**Comment by thomas-fossati** [comment]
I can take a stab at this.  By "2-level delegation diagram" you mean the colourful diagram we used in the discussion with Sanjay and Fred?  Or a more traditional sequence diagram along the same lines?

**Comment by yaronf** [comment]
I had the colorful diagram in mind. But not if it takes tons of effort to adapt it to a more general setting.
