### ISSUE TITLE
EtM and related cipher suites

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#473]
Latest message on the thread is https://mailarchive.ietf.org/arch/msg/uta/PPJzJ5kz9UM6STIjuz07-oiD5Qc/

**Comment by yaronf** [comment]
My opinion: we cannot add any cipher suite at this point without reopening the doc (a repeat WGLC), and IMO we should not be doing that.

The most we can do right now is add a statement like, if you use a non-GCM cipher suite, you MUST use EtM.

**Comment by thomas-fossati** [comment]
So something like:

_"A cipher suite using CBC (cipher block chaining) mode (e.g., `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`) MUST NOT be used unless the encrypt_then_mac extension {{!RFC 7366}} is also successfully negotiated."_
