### ISSUE TITLE
Improve message flow diagram

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#50]
Fig. 1: specifically, add response messages.

**Comment by thomas-fossati** [comment]
Figure 1 is in the overview section, so it's not that unreasonable for it to stay high level -- a bit like the diagram in [section 4 of ACME](https://tools.ietf.org/html/rfc8555#section-4).

Now that you made me look at it more closely I think that yes, we are missing a couple of lines:
1. the acknowledgement from right to left after the CSR+Signature message
2. the request for the certificate as plain GET from NDC to ACME Server.
