### ISSUE TITLE
Question: Requirement for server state 

### ISSUE THREAD

**Issue by dcow** [yaronf/I-D#61]
Hello @yaronf . I have a design question: what's the motivation for specifying a mechanism requiring server state rather than allowing clients to drive renewal? What I mean is, why does the server need to do work in absence of a client asking for a renewal? Signing a certificate is easy can can be done inline during a request. Authentication can be accomplished by requiring mTLS on a renewal endpoint. This is, for example, how we handle renewals in [step-ca](https://github.com/smallstep/certificates) (an ACME compliant CA implementation).

**Comment by dcow** [comment]
Another thought that comes to mind: perhaps in the same way ACME is flexible and supports various challenge mechanisms, there could be various renewal mechanisms.

**Comment by thomas-fossati** [comment]
Hi David, the design decision to go server-side was heavily influenced by the "credential delegation" use case that motivated STAR in the first place.  If you are curious, you can have a look at the [initial discussion on the ACME mailing list](https://mailarchive.ietf.org/arch/browse/acme/?gbt=1&index=I3vOEE901HUuYxTgck7KVXYW0l8) and in particular to [Andrew Ayer's tweak](https://mailarchive.ietf.org/arch/msg/acme/amrVJ_TV21wY9cVJ1sX89BZr92Y/) to Yaron's proposal 1 which oriented the final design.

**Comment by dcow** [comment]
Thanks @thomas-fossati . Looks I've got some catching/reading up to do.

**Comment by thomas-fossati** [comment]
> Another thought that comes to mind: perhaps in the same way ACME is flexible and supports various challenge mechanisms, there could be various renewal mechanisms.

Damn, we should have had this conversation a couple of years back.

**Comment by yaronf** [comment]
Also in general, when balancing costs, I think it makes sense to simplify the client at the cost of making the server more complicated. Thank you @dcow for asking, and @thomas-fossati for digging up ancient history!
