### ISSUE TITLE
Order for non-STAR certs

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#63]
In section "Order Object on the NDC-IdO side" we say:
```
- MUST contain an "auto-renewal" object and inside it, the fields
  listed in Section 3.1.1 of {{!RFC8739}};
```
but this is only applicable to STAR-based delegation.

This needs fixing to account for "Delegation of Non-STAR Certificates".

**Comment by yaronf** [comment]
Done in Sec. 2.4 of -04.
