### ISSUE TITLE
ID nits

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#69]
** Obsolete normative reference: RFC 6844 (Obsoleted by RFC 8659)

  == Outdated reference: A later version (-04) exists of
     draft-ietf-cdni-interfaces-https-delegation-03

  -- Unexpected draft version: The latest known version of 
     draft-ietf-stir-cert-delegation is -02, but you're referring to -03.

**Comment by yaronf** [comment]
This message re: `draft-ietf-stir-cert-delegation` is a bug in I-D nits!
