### ISSUE TITLE
Section 3.1 - challenges with the template syntax

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#83]
-- Where is the normative format for the syntax?  Section 3.1 points to Appendix B which lists JSON schema whose format is specified "draft 7 of JSON Schema, which may not be the latest version of the corresponding Internet Draft [I-D.handrews-json-schema] at the time of publication".  As far as I can tell "draft 7 of JSON Schema" seems to resolve to https://json-schema.org/specification-links.html which points back to draft-handrews-json-schema.  This draft appears to be an expired, individual draft codifying.  This ambiguity and lack of stable reference is problematic.

[Edited to move text on mappings to #94]

**Comment by yaronf** [comment]
We should say this is specifically (the expired) `draft-handrews-json-schema-validation-01` - note this is different from the handrews draft we currently cite! And not "the latest version".

Need to add a table with the mapping into X.509 fields (refs to RFC 5280, as in Sec. 5.5). Do we include the Sec. 5.5 extensions in this new table (and remove the Sec. 5.5 table)?

**Comment by thomas-fossati** [comment]
We should say that staying on draft-7 rather than updating to more recent releases  is a conscious decision based on the fact that draft-7 is what is implemented.
