### ISSUE TITLE
Section 5.4 - to registry or not to registry?

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#91]
If there isn't a registry, why are they in the IANA section?  Should we create a registry?

**Comment by yaronf** [comment]
We probably should. But we should also alert the mailing list that we're toying with their IANA real estate.

Also add a Reference column to the table.

**Comment by yaronf** [comment]
* Remove the IANA section
* Remove the "delegated" and "cname" fields from examples and surrounding text.
* Add "cname" into the Delegation object in 2.3.1 (parallel to csr-template).

**Comment by thomas-fossati** [comment]
Thinking a bit more about this: I think we should move the Order's `delegation` attribute inside the `identifier` entry.  This way we allow multiple identifiers (which currently has undefined semantics) as well as a precise identifier-delegation binding for each.

**Comment by yaronf** [comment]
So we are back to a new IANA registry. Let's discuss.

**Comment by yaronf** [comment]
Back to a new registry.
`identifiers` gets a new attribute `delegation` (mandatory), a URL for a delegation object that must be checked relative to the identifier. 
`cname` goes away. Instead, it goes into sec. 2.3.1 (`delegation` object), parallel to `csr-template`.
