### ISSUE TITLE
Section 5.5 - two considerations on the "type" column

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#93]
Per the definition of the "type" column:

-- Formally, what is a JSON Schema snippet?  In particular, the three pre-loaded values reference seem to reference "Appendix B" which doesn't seem like a "snippet" (it containing a fully valid and well-formed XML file).

-- The registration policy is "expert review" so in theory a document is not needed.  Is the thinking that the registry row could contain a bare JSON snippet?

**Comment by yaronf** [comment]
Quoting my response to Roman:
> The notion of "snippet" is actually well defined when we say, "a JSON Schema snippet that defines a type". Formally this is a valid JSON object with a "type" attribute, per draft-handrews-json-schema-validation-01 Sec. 6.1.1.

And I think that yes, it can be a bare "type" JSON object.

**Comment by yaronf** [comment]
On second thoughts, IANA registries do not often contain raw type definitions - or other text for that matter. Will change to be a reference to a JSON Schema definition.
