### ISSUE TITLE
Section 5.5 - more clarity around subjectAltName mapping

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#94]
What does "(only for the supported name formats)" mean in the "Mapping to X.509" of subjectAltName

**Comment by yaronf** [comment]
Per the CSR template schema, these formats are IPv4 address, IPv6 address, DNS name, email address.

**Comment by yaronf** [comment]
-- Accepting the Json schema as is, there is no annotation on the fields. The field names very much look like X.509 fields but the text provides no guidance on how they should be interpreted to create a CSR beyond explaining "**", "*" and what is mandatory. I would have expected a field mapping but the text explicitly says "The mapping between X.509 CSR fields and the template will be defined in a future revision of this document.". (moved here from #83)

**Comment by yaronf** [comment]
Need to add a table with the mapping into X.509 fields (refs to RFC 5280, as in Sec. 5.5). Do we include the Sec. 5.5 extensions in this new table (and remove the Sec. 5.5 table)?
