### ISSUE TITLE
Figure 1 and 8 - improve consistency

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#97]
In the spirit of consistency, consider if the CA should be named the "CA Server" (per figure 1) or "ACME server" (per figure 8).

**Comment by yaronf** [comment]
We also use the term "ACME CA" several times. So it's not just the figures.

**Comment by yaronf** [comment]
RFC 8555 only uses "ACME CA" once! They use "ACME server" frequently (lowercase s), and interchangeably with "CA".

We also have "ACME STAR CA".

Will adopt the conventions of 8555, so "ACME server" and "CA".
